name: Build and Deploy To GH Pages
on:
  push:
    branches:
      - main
jobs:
  gh-pages:
    name: gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.8"

      - name: Install and Build
        run: |
          npm ci
          npm build
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: dist